<?php
/**
 * Default template for displaying the customer pricing
 * in place of base price for the store page
 * 
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange_Addon_Customer_Pricing
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/ directory located
 * in your theme.
*/
?>
<?php do_action( 'it_exchange_content_store_before_customer_pricing_price_element' ); ?>
<div class="it-exchange-customer-pricing">
	<?php it_exchange( 'customer-pricing', 'customer-pricing' ); ?>
	<div class="it-exchange-product-price">
		<p><?php it_exchange( 'customer-pricing', 'base-price', array( 'show-or-more' => false ) ); ?></p>
	</div>
</div>
<?php do_action( 'it_exchange_content_store_after_customer_pricing_price_element' ); ?>